---
title: "YouHeal Table 1 Sociodemographics"
author: "Dom"
date: "11/5/2018"
output: html_document
---

```{r, results = "hide"}
#Initialize libraries to be used
library(tidyverse)
  #tidyverse causes LaTeX error when outputting to PDF...change to "xelatex" from PDF options. Or use      HTML
library(haven)
library(psych)
library(ggplot2)
library(dplyr)
library(readr)
library(stringr)

#make a table 1
#https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html
library(tableone)
library(readr)

#need to label variables
library(Hmisc)
```

#Get Clean Data
```{r}
#load dataset
setwd("/Volumes/GoogleDrive/My Drive/20180823 YouHeal/Data/!Clean Datasets")
load("Phase1_Scored.RData")
```

#Identify sociodemographic data variables
```{r}
#subset subject ID and sociodemographic variables
socdem <- cbind(YH_phase1_score[,1], YH_phase1_score[,14:21])

myVars <- c(
  "ID",
  "Sex", 
  "Age", 
  "Primary Language", 
  "Secondary Language",
  "English Proficiency", 
  "Race",
  "City",
  "Zip"
)
colnames(socdem) <- myVars
glimpse(socdem)
```

#Make a table 1 of the composite scores
```{r}
#make table 1
tab1 <- CreateTableOne(data = socdem, vars = c("Age", "Sex", "Primary Language", "Race", "City"))

tab1[["ContTable"]]
tab1[["CatTable"]]
```