---
title: "YouHeal Visualize Survey"
author: "Dom"
date: "10/15/2018"
output: html_document
---

```{r, results = "hide"}
# Initialize libraries to be used
library(tidyverse)
  # tidyverse causes LaTeX error when outputting to PDF...change to "xelatex" from PDF options. Or use      HTML
library(haven)
library(psych)
library(ggplot2)
library(dplyr)
library(readr)
library(stringr)

# make a table 1
#   https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html
library(tableone)
library(readr)

# need to label variables
library(Hmisc)

# scoring the physical and diet survey
library(scales)
```

#Get Clean Data
```{r}
#load dataset
setwd("/Volumes/GoogleDrive/My Drive/20180823 YouHeal/Data/!Clean Datasets")
load("Phase1_Scored.RData")
```

# Score Diet and Physical Activity Survey
## Items Q7 to Q25
```{r}

## wrangle data into long format

  # create dataset containing only the YRBS items
  YRBS_wide <- YH_phase1_score %>% 
    select(ID, contains("YRBS")) 

  # get a vector of column names, dropping base/flup prefix
  yrbsVars <- YRBS_wide %>% 
    select(ID, starts_with("base")) %>% 
    colnames() %>% 
    str_remove("base_")
  
  # reassign variable names
  
    # baseline
    YRBS_wide_base <- YRBS_wide %>% 
      select(ID, starts_with(("base")))
    colnames(YRBS_wide_base) <- yrbsVars
    # make a new variable for time of measurement, at baseline
    YRBS_wide_base$time <- 0
    
    # follow-up
    YRBS_wide_flup <- YRBS_wide %>% 
      select(ID, starts_with(("flup")))
    colnames(YRBS_wide_flup) <- yrbsVars
    # make a new variable for time of measurement, at follow-up
    YRBS_wide_flup$time <- 1

    # now that variables have common names for different time points,
    # merge baseline and follow-up data
    YRBS_long <- bind_rows(YRBS_wide_base, YRBS_wide_flup)
    
  # make time variable a factor
  YRBS_long$time <- YRBS_long$time %>% 
    factor(
      levels = c(0, 1),
      labels = c("Baseline", "Follow-up"),
      ordered = TRUE
      )
    
  #reorder variables
  YRBS_long <- YRBS_long %>%
    select(ID, time, everything())

  
## Rescore Diet and Physical Activity Survey (items Q7 to Q25)
##   so higher score is associated with better health
##   and lower score is associated with worse health 
glimpse(YRBS_long)

  # make factor variables numeric
  YRBS_long_factor <- YRBS_long %>%
    # convert all scoring variables to numeric
    mutate_at(
      vars(-ID, -time),
      funs(as.numeric)
      )

  # YRBS variables already in correct order: healthy higher score
 
    yrbsVars2 <- YRBS_long_factor %>% 
      select(ID, time, 
             Q18_YRBS_allergy)
    
    yrbsVars4 <- YRBS_long_factor %>% 
      select(ID, time, 
             Q24_YRBS_sportsteam)
    
    yrbsVars6 <- YRBS_long_factor %>% 
      select(ID, time, 
             Q23_YRBS_pe)
    
    yrbsVars7 <- YRBS_long_factor %>% 
      select(ID, time, 
             Q8_YRBS_fruit, Q9_YRBS_salad, Q10_YRBS_potato, Q11_YRBS_carrot, 
             Q12_YRBS_otherveg, Q15_YRBS_water, Q16_YRBS_milk)
    
    yrbsVars8 <- YRBS_long_factor %>% 
      select(ID, time, 
             Q17_YRBS_breakfast, Q19_YRBS_physical, Q20_YRBS_strength)
  
  # YRBS variables to be reversed so healthier will be higher score
  
    yrbsVars5R <- YRBS_long_factor %>% 
      select(ID, time, 
             Q25_YRBS_concussion)
    
    yrbsVars7R <- YRBS_long_factor %>% 
      select(ID, time, 
             Q7_YRBS_juice, Q13_YRBS_soda, Q14_YRBS_sportdrink, 
             Q21_YRBS_tv, Q22_YRBS_screentime)
  
    
  # rescore variables to 0-100 point scale based off all possible factor levels
  
    # rescale items with 4 possible answers
    yrbsVars2[,3] <- yrbsVars2[,3] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 0
          x[x == 2] <- 100
          x[x == 3] <- NaN
          x
          })
    
    # rescale items with 4 possible answers
    yrbsVars4[,3] <- yrbsVars4[,3] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 0
          x[x == 2] <- 1 * 100/3
          x[x == 3] <- 2 * 100/3
          x[x == 4] <- 100
          x
          })

    # rescale items with 6 possible answers
    yrbsVars6[,3] <- yrbsVars6[,3] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 0
          x[x == 2] <- 20
          x[x == 3] <- 40
          x[x == 4] <- 60
          x[x == 5] <- 80
          x[x == 6] <- 100
          x
          })

    # rescale items with 7 possible answers
    yrbsVars7[,3:9] <- yrbsVars7[,3:9] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 0
          x[x == 2] <- 1 * 100/6
          x[x == 3] <- 2 * 100/6
          x[x == 4] <- 3 * 100/6
          x[x == 5] <- 4 * 100/6
          x[x == 6] <- 5 * 100/6
          x[x == 7] <- 100
          x
          })

    # rescale items with 8 possible answers
    yrbsVars8[,3:5] <- yrbsVars8[,3:5] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 0
          x[x == 2] <- 1 * 100/7
          x[x == 3] <- 2 * 100/7
          x[x == 4] <- 3 * 100/7
          x[x == 5] <- 4 * 100/7
          x[x == 6] <- 5 * 100/7
          x[x == 7] <- 6 * 100/7
          x[x == 8] <- 100
          x
          })
    
    # rescale items with 5 possible answers, reversed
    yrbsVars5R[,3] <- yrbsVars5R[,3] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 100
          x[x == 2] <- 75
          x[x == 3] <- 50
          x[x == 4] <- 25
          x[x == 5] <- 0
          x
          })

    # rescale items with 7 possible answers, reversed
    yrbsVars7R[,3:7] <- yrbsVars7R[,3:7] %>%
        sapply(FUN = function(x) {
          x[x == 1] <- 100
          x[x == 2] <- 5 * 100/6
          x[x == 3] <- 4 * 100/6
          x[x == 4] <- 3 * 100/6
          x[x == 5] <- 2 * 100/6
          x[x == 6] <- 1 * 100/6
          x[x == 7] <- 0
          x
          })

    
    # rejoin all the scaled items together
    YRBS_long_100 <- yrbsVars2 %>%
      inner_join(yrbsVars4, by = c("ID", "time")) %>% 
      inner_join(yrbsVars6, by = c("ID", "time")) %>% 
      inner_join(yrbsVars7, by = c("ID", "time")) %>% 
      inner_join(yrbsVars8,   by = c("ID", "time")) %>% 
      inner_join(yrbsVars5R,  by = c("ID", "time")) %>% 
      inner_join(yrbsVars7R,   by = c("ID", "time"))
    
    # reorder variables so in proper order
    YRBS_long_100 <- YRBS_long_100 %>% select(ID, time, yrbsVars)
    
    # make into tibble
    YRBS_long_100 <- as.tibble(YRBS_long_100)
    
 
## calculate composite scores: overall, diet, physical activity
    
  # identify variables in each composite
    
    # overall composite
    yrbsVarsAll <- YRBS_long %>% 
      select(starts_with("Q"), -Q18_YRBS_allergy, -Q23_YRBS_pe, -Q24_YRBS_sportsteam, -Q25_YRBS_concussion) %>% 
      colnames()
  
    # diet composite
    yrbsVarsDiet <- c("Q7_YRBS_juice", "Q8_YRBS_fruit", "Q9_YRBS_salad", "Q10_YRBS_potato",
                      "Q11_YRBS_carrot", "Q12_YRBS_otherveg", "Q13_YRBS_soda", "Q14_YRBS_sportdrink",
                      "Q15_YRBS_water", "Q16_YRBS_milk", "Q17_YRBS_breakfast") 
    
    # physical activity composite
    yrbsVarsPhys <- c("Q19_YRBS_physical", "Q20_YRBS_strength", "Q21_YRBS_tv", "Q22_YRBS_screentime")
    
  # calculate composties
    
    # overall composite
    YRBS_compAll <- YRBS_long_100 %>%
      select(yrbsVarsAll) %>%
      mutate(
        compAll = apply(., 1, function(row){ mean(row, na.rm = TRUE) })
        ) %>% 
      select(compAll)


    # diet composite
    YRBS_compDiet <- YRBS_long_100 %>%
      select(yrbsVarsDiet) %>%
      mutate(
        compDiet = apply(., 1, function(row){ mean(row, na.rm = TRUE) })
        ) %>% 
      select(compDiet)

    # physical activity composite
    YRBS_compPhys <- YRBS_long_100 %>%
      select(yrbsVarsPhys) %>%
      mutate(
        compPhys = apply(., 1, function(row){ mean(row, na.rm = TRUE) })
        ) %>% 
      select(compPhys)

    # combine all composites into single data frame
    YRBS_compScores <- YRBS_long_100 %>% 
      select(ID, time) %>% 
      cbind(YRBS_compAll, YRBS_compDiet, YRBS_compPhys)
  
# PI wants to remove the following survey questions: 18. Allergies, 23. PE, 24. Sport teams, 25. Concussions
# but only makes sense to remove allergy
```


#Reorganize composite data so can compare baseline and follow up
```{r}
#locate composite variables in dataset
#YH_phase1_score[,1]
#YH_phase1_score[,110:119]

#subset by time into working data frames
composite_base <- cbind(YH_phase1_score[,1],YH_phase1_score[,110],YH_phase1_score[,112:115],YH_phase1_score$base_TSF_avg,YH_phase1_score$base_WC_avg)
composite_flup <- cbind(YH_phase1_score[,1],YH_phase1_score[,111],YH_phase1_score[,116:119],YH_phase1_score$flup_TSF_avg,YH_phase1_score$flup_WC_avg)

#create new variable names, not associated with time, assign
composite_vars <- c("ID","Q26Q35_se_composite","Q36Q47_em_composite","Q41Q43_em_individual","Q36Q40_em_organizational","Q42Q47_em_community","Avg_TSF","Avg_WC")
colnames(composite_base) <- composite_vars
colnames(composite_flup) <- composite_vars

#create a dummy variable for time
composite_base$time <- 0
composite_flup$time <- 1

composite <- rbind(composite_base, composite_flup)

#make body measurements doubles
composite$Avg_TSF <- as.double(composite$Avg_TSF)
composite$Avg_WC <- as.double(composite$Avg_WC)


# combine with YRBS diet and physical activity composites

  # make all id and time variables to be the same numerics (from factors)
  composite$ID <- as.integer(composite$ID)
  composite$time <- as.factor(composite$time)
  YRBS_compScores$time <- as.factor(YRBS_compScores$time)
  composite$time <- as.numeric(composite$time)
  YRBS_compScores$time <- as.numeric(YRBS_compScores$time)
  
  # check to make sure matched up correctly
  cbind(composite$ID,YRBS_compScores$ID,composite$time,YRBS_compScores$time)

# final dataset with all composite scores to be considered
composite_all <- composite %>%
  inner_join(YRBS_compScores, by = c("ID","time")) %>% 
  select(ID, time, everything()) %>% 
  mutate(
    # format time variable as factor with labels
    time = factor(time, levels = c(1,2), labels = c("Baseline", "Follow-up"))
  )
```

#Boxplots comparing composite scores at baseline and follow up
```{r}
setwd("/Volumes/GoogleDrive/My Drive/20180823 YouHeal/Figures & Tables/Composite Boxplots")

summary(composite_all)

boxit <- function(score, titles, color){
 boxedup <- ggplot(composite_all, aes(x = as.factor(time), y = score)) + geom_boxplot(fill = color, alpha = 0.2) + 
  ggtitle(titles) +
  xlab("Time") +
  ylab("Score") +
  
  theme( 
    #Change size of axes labels
    text = element_text(size = 14),
    
    axis.text.x = element_text(size = 10),
    
    #clean up the gridlines and background
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black")
  )
  
  #saveplot
  ggsave(paste(titles,".png",sep = ""), width = 5, height = 3 , boxedup)
}

#self efficacy
boxit(score = composite_all$Q26Q35_se_composite, titles = "Self Efficacy Composite", color = "gray")

#empowerment
boxit(score = composite_all$Q36Q47_em_composite, titles = "Empowerment Composite",color = "blue")
boxit(score = composite_all$Q41Q43_em_individual, titles = "Empowerment Individual Items", color = "blue")
boxit(score = composite_all$Q36Q40_em_organizational, titles = "Empowerment Organizational Items", color = "blue")
boxit(score = composite_all$Q42Q47_em_community, titles = "Empowerment Community Items", color = "blue")

#anthropometric measures
boxit(score = composite_all$Avg_TSF, titles = "Average Tricep Skin Fold (mm)", color = "green")
boxit(score = composite_all$Avg_WC, titles = "Average Waist Circumference (cm)", color = "green")


boxit100 <- function(score, titles, color){
 boxedup <- ggplot(composite_all, aes(x = as.factor(time), y = score)) + geom_boxplot(fill = color, alpha = 0.2) +
   scale_y_continuous(limits = c(40,80)) +
   ggtitle(titles) +
   xlab("Time") +
   ylab("Score") +
  
  theme( 
    #Change size of axes labels
    text = element_text(size = 14),
    
    axis.text.x = element_text(size = 10),
    
    #clean up the gridlines and background
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black")
  )
  
  #saveplot
  ggsave(paste(titles,".png",sep = ""), width = 5, height = 3 , boxedup)
}

# YRBS diet and physical activity scores
boxit100(score = composite_all$compAll, titles = "YRBS Combined Diet & Activity Composite", color = "red")
boxit100(score = composite_all$compDiet, titles = "YRBS Diet Composite", color = "red")
boxit100(score = composite_all$compPhys, titles = "YRBS Physical Activity Composite", color = "red")
```


#Make a table 1 of the composite scores
```{r}
#assign vector of variable names to be in table 1
myVars <- c(
  "compDiet",
  "compPhys",
  "compAll",
  "Q26Q35_se_composite", 
  "Q36Q47_em_composite", 
  "Q41Q43_em_individual", 
  "Q36Q40_em_organizational", 
  "Q42Q47_em_community",
  "Avg_TSF",
  "Avg_WC"
)

#make table 1
tab1 <- CreateTableOne(vars = myVars, strata = "time" , data = composite_all)
tab1

#save it as excel file
setwd("/Volumes/GoogleDrive/My Drive/20180823 YouHeal/Figures & Tables/Composite Boxplots")
```
